# Base model configuration
model:
  name: "meta-llama/Llama-3.2-1B-Instruct"  # Small but powerful base model
  max_length: 256
  temperature: 0.7
  top_p: 0.9

# Training configuration
training:
  batch_size: 4
  learning_rate: 2e-5
  num_epochs: 3
  warmup_steps: 500
  gradient_accumulation_steps: 4
  weight_decay: 0.01
  
# Medical domain specific settings
medical:
  disclaimer: "This model provides general information only. Always consult healthcare professionals for medical advice."
  response_constraints:
    max_length: 300
    prohibited_topics:
      - prescription_medications
      - specific_drug_recommendations
      - diagnostic_conclusions
    required_elements:
      - general_information
      - lifestyle_recommendations
      - professional_consultation_advice

# Dataset configuration
dataset:
  train_path: "data/medical_qa_train.json"
  eval_path: "data/medical_qa_eval.json"
  validation_split: 0.1 